version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    image: ecs-sample/nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
